#! python3
"""
scrape_poe_cards.py - scrapes poe divination cards from the wiki using the SMW API.
"""

import requests, re, datetime, time, json, os

SCRIPTDIR = os.path.dirname(os.path.abspath(__file__))

# Regex magic! I recommend using https://regex101.com to make it more readable.

regex_wikilinks2 = re.compile(r'\[\[([^\]\|]*)\]\]|\[\[([^\]\|]* Map)\|[^\]\|]*\]\]|\[\[[^\]\|]*\|([^\]\|]*)\]\]')
"""
matches formats "[[text]]" or "[[wikipage|text]] and stores "text" as capture group 1 or 3, respectively.
For links to map articles the first part is matched, so that "map" is included. This is stored as capture group 2.
[[Core Map|Core]] -> Core Map
[[The Harvest (area)|The Harvest]] -> The Harvest
Sold by [[Zana]] -> Zana
Drops in [[map]]s -> map

Since only one capture group is filled each time, using all together in a replacement like r'\1\2\3' turns
all match variants into the desired text.
"""

def remove_wiki_formats(text):
	if text:
		text = text[0]
	else:
		return None
	
	text = text.replace(']], [[', ']]><[[')
	list = text.split('><')
	# Splitting the text into a list/array without removing the [[ ]] link syntax, so that the regex below has limiters.
	# Simply splitting on ', ' does not work because there are items with a comma in the name.
	for index, entry in enumerate(list):
		list[index] = regex_wikilinks2.sub(r'\1\2\3', entry)	# remove wiki links with regular expression. See the start of the script.
	
	list.sort()
	return list


def clean_up_api_results(api_results):
	"""
	Takes the API result and turns it into a list of json objects.
	At this stage the mods are still in the original wiki format.
	"""
	
	item_names = list(api_results.keys())
	item_names.sort()
	partial_item_list = []
	for item_name in item_names:
		obj = {}
		obj['name'] = item_name
		obj['location'] = remove_wiki_formats(api_results[item_name]['printouts']['Has area drop restriction HTML'])
		obj['restriction'] = remove_wiki_formats(api_results[item_name]['printouts']['Has drop restriction text'])
		
		partial_item_list.append(obj)
	
	return partial_item_list
	
	
def get_api_results(item_category):
	"""
	This function gets the wiki data for given unique item categories.
	It uses the wiki's SMW API and requests json format.
	See this HTML version to get a better idea how the API response is structured:
	https://pathofexile.gamepedia.com/api.php?action=askargs&parameters=limit%3D500&conditions=Has%20item%20class::Divination%20Card&printouts=Has%20area%20drop%20restriction%20HTML|Has%20drop%20restriction%20text
	"""
	
	print('Getting data for ' + item_category)
	r = requests.get('https://pathofexile.gamepedia.com/api.php?action=askargs&parameters=limit%3D500&conditions=Has%20item%20class::' + item_category + '&printouts=Has%20area%20drop%20restriction%20HTML|Has%20drop%20restriction%20text&format=json')
	rj = r.json()
	api_results = rj['query']['results']
	
	return clean_up_api_results(api_results)


def get_wiki_data(item_categories):
	data_list = []
	for category in item_categories:
		data_list.extend(get_api_results(category))
	
	print('')
	return data_list


def convert_to_AHK_script_format(all_data):
	"""
	This function takes the raw API data and converts it into lines that are readable by the PoE ItemInfo Script.
	"""
	
	new_data = []
	for card in all_data:
		line = 'divinationCardList["' + card['name'] + '"] := "'
		
		if card['location']:
			line += 'Drop Locations:'
			loc_map = []
			loc_area = []
			for loc in card['location']:
				if re.search(" Map$", loc):
					loc_map.append(loc)
				else:
					loc_area.append(loc)
			line += '`n ' + '`n '.join(loc_map + loc_area)
		else:
			if not card['restriction']:
				line += 'No drop information available'
		
		if card['restriction']:
			if card['location']:
				line += '`n'
			line += 'Drop Restrictions:'
			for restr in card['restriction']:
				line += '`n ' + restr.strip()
		
		line += '"'
		new_data.append(line)
	
	return new_data


def define_file_header():
	"""
	info headers for DivinationCards.txt

	:return: list
	"""
	data = []
	d = datetime.datetime.now()
	now_time = d.strftime('%Y-%m-%d at %H:%M:%S')
	data.append('; Data from https://pathofexile.gamepedia.com/Path_of_Exile_Wiki using the SMW API.')
	data.append('; Comments can be made with ";", blank lines will be ignored.')
	data.append(';')
	data.append('; This file was auto-generated by scrape_poe_cards.py on {}'.format(now_time) + '\n')
	data.append('divinationCardList := Object()\n')
	data.append('divinationCardList["Unknown Card"] := "Card not recognised or not supported"\n')

	return data


def write_list_to_lines(new_data):
	file = open(SCRIPTDIR + '\\DivinationCardList.txt', 'a+b')  # opens file for writing
	for row in new_data:
		file.write(row.encode('cp1252'))
		file.write(b'\n')
	file.close()


def main():
	item_categories = ['Divination Card']
	open(SCRIPTDIR + '\\DivinationCardList.txt', 'w').close()  # create file (or overwrite it if it exists)
	write_list_to_lines(define_file_header())
	data_list = get_wiki_data(item_categories)
	new_data = convert_to_AHK_script_format(data_list)
	write_list_to_lines(new_data)


startTime = datetime.datetime.now()
main()
print('\nProgram execution time: ',(datetime.datetime.now() - startTime))
